# Mustererkennung/Machine Learning - Assignment 6



In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

### Load the spam dataset:

In [4]:
data = np.array(pd.read_csv('./spambase/spambase.data', header=None))

X = data[:,:-1] # features
y = data[:,-1] # Last column is label

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, shuffle=True, stratify=y)


In [22]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(X_train[1])
print(y_train[1])

(3450, 57)
(1151, 57)
(3450,)
(1151,)
[ 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     1.14   0.     0.     0.     0.     0.     0.     2.29   0.
  0.     0.     0.     0.     1.14   1.14   0.     0.     0.     0.
  1.14   0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     2.29   0.     0.     0.     0.     0.     0.
  0.     0.596  0.     0.198  2.133 14.    64.   ]
0.0


In [10]:
class Node:
    threshold = 0
    data = None
    
    left_child = None
    right_child = None

    def __init__(self, threshold, data):
        self.threshold = threshold
        self.data = data
        
    def set_children(self, left_child, right_child):
        self.left_child = left_child
        self.right_child = right_child
        
node = Node(3, np.array([1]))
print(node.threshold)

3


In [55]:
def square(num):
    return pow(num, 2)

def cal_Q_tot(c1, c2, y_1, y_2):
    res = 0
    
    for i in y_1:
        res += square(i - c1)
        
    for i in y_2:
        res += square(i - c2)
        
    return res

class Decision_tree:
    root = None
    
    def __init__(self, root):
        self.root = root
        
    def inOrder(self, node):
        if node == None:
            return None
        inOrder(node.leftChild)
        print(node.threshold)
        inOrder(node.rightChild)
        
    def make_decision_tree(self):
        data = self.root.data
        pass
        
    def impurity(self, x_data, y_data):
        # number and dimension of datas
        # 2,4
        length = x_data.shape[0]
        dimension = x_data.shape[1]
        
        data_counter = 0
        dim_counter = 1
        cell_in_table = dimension * (length - 1)
        res = np.zeros((cell_in_table, 5))
        
        for i in range(dimension):
            for j in range(length - 1):
                
                print("data_counter: " + str(data_counter))
                res[data_counter][0] = i + 1
                print(res[data_counter][0])
                
                if j + 1 <= length - 1:
                    z = (x_data[j][i] + x_data[j + 1][i]) / 2.0
                    if(j == 1):
                        print("z: " + str(z))
                        print("j: " + str(j))
                        print(x_data[j][i])
                        print(x_data[j+1][i])
                    res[data_counter][1] = z

                    y_1 = y_data[:j + 1]
                    y_2 = y_data[j + 1:]
#                     print("y1 ", end='')
#                     print(y_1)
#                     print(y_2)
                    c1 = np.average(y_1)
                    c2 = np.average(y_2)

                    res[data_counter][2] = c1
                    res[data_counter][3] = c2

                    Q_tot = cal_Q_tot(c1, c2, y_1, y_2)
                    res[data_counter][4] = Q_tot
                
                data_counter += 1
            dim_counter += 1
        return res
        
        
        
tree = Decision_tree(node)
print(tree.impurity(np.array([[1,1],[2,3],[3,7],[4,5]]), np.array([3,5,6,2.5])))

data_counter: 0
1.0
data_counter: 1
1.0
z: 2.5
j: 1
2
3
data_counter: 2
1.0
data_counter: 3
2.0
data_counter: 4
2.0
z: 5.0
j: 1
3
7
data_counter: 5
2.0
[[1.         1.5        3.         4.5        6.5       ]
 [1.         2.5        4.         4.25       8.125     ]
 [1.         3.5        4.66666667 2.5        4.66666667]
 [2.         2.         3.         4.5        6.5       ]
 [2.         5.         4.         4.25       8.125     ]
 [2.         6.         4.66666667 2.5        4.66666667]]


In [46]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print(counts)
print(np.argmax(counts))
print(np.average(a))
print(a[5:])
print(a)

[0 6 4 2]
1
1.6666666666666667
[1 1 1 3 2 2 1]
[1 2 3 1 2 1 1 1 3 2 2 1]


In [30]:
temp = np.array([[1],[3]])
i = 1
#temp[i][1] = 2
print(square(4))

16
